Bevy 0.2 support
StarArawn/bevy_tiled pull request #17
Opened 2020-09-25 13:48 UTC by cyclopunk

Hey-o!

I just started to work with Tiled on my project (https://github.com/insrcd/labyrinth-game) and wanted try out bevy-tiled. Noticed that it hasn't been moved over to the 0.2.x Transform changes. This should at least get it moving. I know a few other folks are looking for this on the Discord. I tested it out with the examples and things seem to render just fine, not sure if I missed something though.

This should also resolve #16

2020-09-28 12:24 UTC, StarArawn requested changes
This looks good please just fix the merge conflicts that popped up and I'll merge ASAP.

2020-09-28 15:42 UTC, insrcd commented
Should be all set, fixed a small issue with the example as well as it hadn't moved over to the TiledMapCenter struct yet.

2020-09-28 15:48 UTC, insrcd commented
Looks like iso_main needs it to, will grab that.

2020-09-29 13:28 UTC, StarArawn approved these changes

2020-09-29 13:28 UTC, merged